version: "3"

services:
  api:
    env_file:
      - .env
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ./:/app
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "study-api"
    ports:
      - "5432:5432"
